version: 2

project_name: scat

builds:
  - main: .
    binary: scat
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/rebaze/starter-sbom-toolchain/cmd.version={{.Version}}
      - -X github.com/rebaze/starter-sbom-toolchain/cmd.commit={{.Commit}}
      - -X github.com/rebaze/starter-sbom-toolchain/cmd.date={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

brews:
  - repository:
      owner: rebaze
      name: homebrew-tap
    homepage: https://github.com/rebaze/starter-sbom-toolchain
    description: Software Composition Analysis CLI — SBOM, vulnerability, and license scanning
    license: Apache-2.0
    install: |
      bin.install "scat"
    test: |
      system "#{bin}/scat", "version"
    dependencies: []
